TrajectoryPlannerROS:
  max_vel_x: 1
  min_vel_x: 0.01
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.0
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  yaw_goal_tolerance: 0.2
  path_distance_bias: 5

  holonomic_robot: true
  meter_scoring: true