local_costmap:
   global_frame: map
   robot_base_frame: $(arg base_frame)
   update_frequency: 5.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   width: 6
   height: 6
   resolution: .05
